
name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: make docker-build

      - name: Lint with ts-standard
        run: make lint
